package bean;
// Generated 15.05.2016 11:05:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Eigentuemer generated by hbm2java
 */
public class Eigentuemer  implements java.io.Serializable {


     private String eigEmail;
     private Adresse adresse;
     private String eigVorname;
     private String eigNachname;
     private Boolean eigKunde;
     private String eigPasswort;
     private Set gebaeudes = new HashSet(0);

    public Eigentuemer() {
    }

	
    public Eigentuemer(String eigEmail, Adresse adresse, String eigPasswort) {
        this.eigEmail = eigEmail;
        this.adresse = adresse;
        this.eigPasswort = eigPasswort;
    }
    public Eigentuemer(String eigEmail, Adresse adresse, String eigVorname, String eigNachname, Boolean eigKunde, String eigPasswort, Set gebaeudes) {
       this.eigEmail = eigEmail;
       this.adresse = adresse;
       this.eigVorname = eigVorname;
       this.eigNachname = eigNachname;
       this.eigKunde = eigKunde;
       this.eigPasswort = eigPasswort;
       this.gebaeudes = gebaeudes;
    }
   
    public String getEigEmail() {
        return this.eigEmail;
    }
    
    public void setEigEmail(String eigEmail) {
        this.eigEmail = eigEmail;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }
    public String getEigVorname() {
        return this.eigVorname;
    }
    
    public void setEigVorname(String eigVorname) {
        this.eigVorname = eigVorname;
    }
    public String getEigNachname() {
        return this.eigNachname;
    }
    
    public void setEigNachname(String eigNachname) {
        this.eigNachname = eigNachname;
    }
    public Boolean getEigKunde() {
        return this.eigKunde;
    }
    
    public void setEigKunde(Boolean eigKunde) {
        this.eigKunde = eigKunde;
    }
    public String getEigPasswort() {
        return this.eigPasswort;
    }
    
    public void setEigPasswort(String eigPasswort) {
        this.eigPasswort = eigPasswort;
    }
    public Set getGebaeudes() {
        return this.gebaeudes;
    }
    
    public void setGebaeudes(Set gebaeudes) {
        this.gebaeudes = gebaeudes;
    }




}


