package bean;
// Generated 15.05.2016 11:05:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gutachter generated by hbm2java
 */
public class Gutachter  implements java.io.Serializable {


     private String gutEmail;
     private Adresse adresse;
     private String gutVorname;
     private String gutNachname;
     private String gutPasswort;
     private Set schadens = new HashSet(0);

    public Gutachter() {
    }

	
    public Gutachter(String gutEmail, Adresse adresse, String gutPasswort) {
        this.gutEmail = gutEmail;
        this.adresse = adresse;
        this.gutPasswort = gutPasswort;
    }
    public Gutachter(String gutEmail, Adresse adresse, String gutVorname, String gutNachname, String gutPasswort, Set schadens) {
       this.gutEmail = gutEmail;
       this.adresse = adresse;
       this.gutVorname = gutVorname;
       this.gutNachname = gutNachname;
       this.gutPasswort = gutPasswort;
       this.schadens = schadens;
    }
   
    public String getGutEmail() {
        return this.gutEmail;
    }
    
    public void setGutEmail(String gutEmail) {
        this.gutEmail = gutEmail;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }
    public String getGutVorname() {
        return this.gutVorname;
    }
    
    public void setGutVorname(String gutVorname) {
        this.gutVorname = gutVorname;
    }
    public String getGutNachname() {
        return this.gutNachname;
    }
    
    public void setGutNachname(String gutNachname) {
        this.gutNachname = gutNachname;
    }
    public String getGutPasswort() {
        return this.gutPasswort;
    }
    
    public void setGutPasswort(String gutPasswort) {
        this.gutPasswort = gutPasswort;
    }
    public Set getSchadens() {
        return this.schadens;
    }
    
    public void setSchadens(Set schadens) {
        this.schadens = schadens;
    }




}


