package bean;
// Generated 15.05.2016 11:05:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Handwerker generated by hbm2java
 */
public class Handwerker  implements java.io.Serializable {


     private String hawEmail;
     private Adresse adresse;
     private Beruf beruf;
     private String hawVorname;
     private String hawNachname;
     private String hawPasswort;
     private Set auftrags = new HashSet(0);

    public Handwerker() {
    }

	
    public Handwerker(String hawEmail, Adresse adresse, Beruf beruf, String hawPasswort) {
        this.hawEmail = hawEmail;
        this.adresse = adresse;
        this.beruf = beruf;
        this.hawPasswort = hawPasswort;
    }
    public Handwerker(String hawEmail, Adresse adresse, Beruf beruf, String hawVorname, String hawNachname, String hawPasswort, Set auftrags) {
       this.hawEmail = hawEmail;
       this.adresse = adresse;
       this.beruf = beruf;
       this.hawVorname = hawVorname;
       this.hawNachname = hawNachname;
       this.hawPasswort = hawPasswort;
       this.auftrags = auftrags;
    }
   
    public String getHawEmail() {
        return this.hawEmail;
    }
    
    public void setHawEmail(String hawEmail) {
        this.hawEmail = hawEmail;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }
    public Beruf getBeruf() {
        return this.beruf;
    }
    
    public void setBeruf(Beruf beruf) {
        this.beruf = beruf;
    }
    public String getHawVorname() {
        return this.hawVorname;
    }
    
    public void setHawVorname(String hawVorname) {
        this.hawVorname = hawVorname;
    }
    public String getHawNachname() {
        return this.hawNachname;
    }
    
    public void setHawNachname(String hawNachname) {
        this.hawNachname = hawNachname;
    }
    public String getHawPasswort() {
        return this.hawPasswort;
    }
    
    public void setHawPasswort(String hawPasswort) {
        this.hawPasswort = hawPasswort;
    }
    public Set getAuftrags() {
        return this.auftrags;
    }
    
    public void setAuftrags(Set auftrags) {
        this.auftrags = auftrags;
    }




}


