-- MySQL Script generated by MySQL Workbench
-- 05/11/16 22:23:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iib2_ue1_2_gruppe1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iib2_ue1_2_gruppe1` ;

-- -----------------------------------------------------
-- Schema iib2_ue1_2_gruppe1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iib2_ue1_2_gruppe1` DEFAULT CHARACTER SET utf8 ;
USE `iib2_ue1_2_gruppe1` ;

-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Beruf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Beruf` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Beruf` (
  `ber_id` INT NOT NULL AUTO_INCREMENT,
  `ber_name` VARCHAR(80) NULL,
  `ber_spezialisierung` VARCHAR(80) NULL,
  PRIMARY KEY (`ber_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Adresse` (
  `adr_id` INT NOT NULL AUTO_INCREMENT,
  `adr_strasse` VARCHAR(45) NULL,
  `adr_hausnummer` VARCHAR(45) NULL,
  `adr_plz` VARCHAR(8) NULL,
  `adr_ort` VARCHAR(45) NULL,
  `adr_land` VARCHAR(45) NULL,
  PRIMARY KEY (`adr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Handwerker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Handwerker` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Handwerker` (
  `haw_email` VARCHAR(50) NOT NULL,
  `haw_vorname` VARCHAR(45) NULL,
  `haw_nachname` VARCHAR(45) NULL,
  `haw_ber_id` INT NOT NULL,
  `haw_adr_id` INT NOT NULL,
  PRIMARY KEY (`haw_email`),
  INDEX `fk_Handwerker_Beruf_idx` (`haw_ber_id` ASC),
  INDEX `fk_Handwerker_Adresse1_idx` (`haw_adr_id` ASC),
  CONSTRAINT `fk_Handwerker_Beruf`
    FOREIGN KEY (`haw_ber_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Beruf` (`ber_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Handwerker_Adresse1`
    FOREIGN KEY (`haw_adr_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Adresse` (`adr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Eigentuemer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Eigentuemer` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Eigentuemer` (
  `eig_email` VARCHAR(50) NOT NULL,
  `eig_vorname` VARCHAR(45) NULL,
  `eig_nachname` VARCHAR(45) NULL,
  `eig_kunde` TINYINT(1) NULL,
  `eig_adr_id` INT NOT NULL,
  PRIMARY KEY (`eig_email`),
  INDEX `fk_Eigentuemer_Adresse1_idx` (`eig_adr_id` ASC),
  CONSTRAINT `fk_Eigentuemer_Adresse1`
    FOREIGN KEY (`eig_adr_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Adresse` (`adr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Gutachter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Gutachter` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Gutachter` (
  `gut_email` VARCHAR(50) NOT NULL,
  `gut_vorname` VARCHAR(45) NULL,
  `gut_nachname` VARCHAR(45) NULL,
  `gut_adr_id` INT NOT NULL,
  PRIMARY KEY (`gut_email`),
  INDEX `fk_Gutachter_Adresse1_idx` (`gut_adr_id` ASC),
  CONSTRAINT `fk_Gutachter_Adresse1`
    FOREIGN KEY (`gut_adr_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Adresse` (`adr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Schadensart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Schadensart` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Schadensart` (
  `sda_id` INT NOT NULL AUTO_INCREMENT,
  `sda_name` VARCHAR(45) NULL,
  PRIMARY KEY (`sda_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Gebaeude`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Gebaeude` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Gebaeude` (
  `gbd_id` INT NOT NULL AUTO_INCREMENT,
  `gbd_name` VARCHAR(45) NULL,
  `gbd_eig_email` VARCHAR(80) NOT NULL,
  `gbd_adr_id` INT NOT NULL,
  PRIMARY KEY (`gbd_id`),
  INDEX `fk_Gebaude_Eigentuemer1_idx` (`gbd_eig_email` ASC),
  INDEX `fk_Gebaude_Adresse1_idx` (`gbd_adr_id` ASC),
  CONSTRAINT `fk_Gebaude_Eigentuemer1`
    FOREIGN KEY (`gbd_eig_email`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Eigentuemer` (`eig_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gebaude_Adresse1`
    FOREIGN KEY (`gbd_adr_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Adresse` (`adr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Schadenslage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Schadenslage` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Schadenslage` (
  `sdl_id` INT NOT NULL AUTO_INCREMENT,
  `sdl_stockwerk` VARCHAR(5) NULL,
  `sdl_raum` VARCHAR(45) NULL,
  `sdl_gbd_id` INT NOT NULL,
  PRIMARY KEY (`sdl_id`),
  INDEX `fk_Schadenslage_Gebaude1_idx` (`sdl_gbd_id` ASC),
  CONSTRAINT `fk_Schadenslage_Gebaude1`
    FOREIGN KEY (`sdl_gbd_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Gebaeude` (`gbd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Schaden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Schaden` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Schaden` (
  `sdn_id` INT NOT NULL AUTO_INCREMENT,
  `sdn_status` ENUM('Mitarbeiter', 'Kunde', 'begutachtet', 'Auftrag', 'erledigt', 'abgelehnt') NULL,
  `sdn_sda_id` INT NOT NULL,
  `sdn_umfang` ENUM('Totalschaden', 'Teilschaden', 'Kleinstschaden') NULL,
  `sdn_sdl_id` INT NOT NULL,
  `sdn_gut_email` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`sdn_id`),
  INDEX `fk_Schaden_Schadensart1_idx` (`sdn_sda_id` ASC),
  INDEX `fk_Schaden_Schadenslage1_idx` (`sdn_sdl_id` ASC),
  INDEX `fk_Schaden_Gutachter1_idx` (`sdn_gut_email` ASC),
  CONSTRAINT `fk_Schaden_Schadensart1`
    FOREIGN KEY (`sdn_sda_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Schadensart` (`sda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schaden_Schadenslage1`
    FOREIGN KEY (`sdn_sdl_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Schadenslage` (`sdl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schaden_Gutachter1`
    FOREIGN KEY (`sdn_gut_email`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Gutachter` (`gut_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Auftrag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Auftrag` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Auftrag` (
  `auf_nummer` INT NOT NULL AUTO_INCREMENT,
  `auf_status` ENUM('angelegt', 'in Bearbeitung', 'erledigt', 'abgelehnt') NULL,
  `auf_haw_email` VARCHAR(50) NOT NULL,
  `auf_sdn_id` INT NOT NULL,
  PRIMARY KEY (`auf_nummer`),
  INDEX `fk_Auftrag_Handwerker1_idx` (`auf_haw_email` ASC),
  INDEX `fk_Auftrag_Schaden1_idx` (`auf_sdn_id` ASC),
  CONSTRAINT `fk_Auftrag_Handwerker1`
    FOREIGN KEY (`auf_haw_email`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Handwerker` (`haw_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auftrag_Schaden1`
    FOREIGN KEY (`auf_sdn_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Schaden` (`sdn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Multimedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Multimedia` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Multimedia` (
  `mmd_id` INT NOT NULL AUTO_INCREMENT,
  `mmd_art` ENUM('Bild', 'Video', 'Memo') NULL,
  `mmd_dateipfad` VARCHAR(80) NULL,
  `mmd_sdn_id` INT NOT NULL,
  PRIMARY KEY (`mmd_id`),
  INDEX `fk_Multimedia_Schaden1_idx` (`mmd_sdn_id` ASC),
  CONSTRAINT `fk_Multimedia_Schaden1`
    FOREIGN KEY (`mmd_sdn_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Schaden` (`sdn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iib2_ue1_2_gruppe1`.`Mitarbeiter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iib2_ue1_2_gruppe1`.`Mitarbeiter` ;

CREATE TABLE IF NOT EXISTS `iib2_ue1_2_gruppe1`.`Mitarbeiter` (
  `mab_email` VARCHAR(50) NOT NULL,
  `mab_vorname` VARCHAR(45) NULL,
  `mab_nachname` VARCHAR(45) NULL,
  `mab_rolle` ENUM('Mitarbeiter', 'Admin') NULL,
  `mab_adr_id` INT NOT NULL,
  PRIMARY KEY (`mab_email`),
  INDEX `fk_Mitarbeiter_Adresse1_idx` (`mab_adr_id` ASC),
  CONSTRAINT `fk_Mitarbeiter_Adresse1`
    FOREIGN KEY (`mab_adr_id`)
    REFERENCES `iib2_ue1_2_gruppe1`.`Adresse` (`adr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
