package mysqlBeans;
// Generated 12.05.2016 22:04:38 by Hibernate Tools 4.3.1



/**
 * Multimedia generated by hbm2java
 */
public class Multimedia  implements java.io.Serializable {


     private Integer mmdId;
     private Schaden schaden;
     private String mmdArt;
     private String mmdDateipfad;

    public Multimedia() {
    }

	
    public Multimedia(Schaden schaden) {
        this.schaden = schaden;
    }
    public Multimedia(Schaden schaden, String mmdArt, String mmdDateipfad) {
       this.schaden = schaden;
       this.mmdArt = mmdArt;
       this.mmdDateipfad = mmdDateipfad;
    }
   
    public Integer getMmdId() {
        return this.mmdId;
    }
    
    public void setMmdId(Integer mmdId) {
        this.mmdId = mmdId;
    }
    public Schaden getSchaden() {
        return this.schaden;
    }
    
    public void setSchaden(Schaden schaden) {
        this.schaden = schaden;
    }
    public String getMmdArt() {
        return this.mmdArt;
    }
    
    public void setMmdArt(String mmdArt) {
        this.mmdArt = mmdArt;
    }
    public String getMmdDateipfad() {
        return this.mmdDateipfad;
    }
    
    public void setMmdDateipfad(String mmdDateipfad) {
        this.mmdDateipfad = mmdDateipfad;
    }




}


