package mysqlBeans;
// Generated 12.05.2016 22:04:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Schadenslage generated by hbm2java
 */
public class Schadenslage  implements java.io.Serializable {


     private Integer sdlId;
     private Gebaeude gebaeude;
     private String sdlStockwerk;
     private String sdlRaum;
     private Set schadens = new HashSet(0);

    public Schadenslage() {
    }

	
    public Schadenslage(Gebaeude gebaeude) {
        this.gebaeude = gebaeude;
    }
    public Schadenslage(Gebaeude gebaeude, String sdlStockwerk, String sdlRaum, Set schadens) {
       this.gebaeude = gebaeude;
       this.sdlStockwerk = sdlStockwerk;
       this.sdlRaum = sdlRaum;
       this.schadens = schadens;
    }
   
    public Integer getSdlId() {
        return this.sdlId;
    }
    
    public void setSdlId(Integer sdlId) {
        this.sdlId = sdlId;
    }
    public Gebaeude getGebaeude() {
        return this.gebaeude;
    }
    
    public void setGebaeude(Gebaeude gebaeude) {
        this.gebaeude = gebaeude;
    }
    public String getSdlStockwerk() {
        return this.sdlStockwerk;
    }
    
    public void setSdlStockwerk(String sdlStockwerk) {
        this.sdlStockwerk = sdlStockwerk;
    }
    public String getSdlRaum() {
        return this.sdlRaum;
    }
    
    public void setSdlRaum(String sdlRaum) {
        this.sdlRaum = sdlRaum;
    }
    public Set getSchadens() {
        return this.schadens;
    }
    
    public void setSchadens(Set schadens) {
        this.schadens = schadens;
    }




}


