package bean;
// Generated 20.06.2016 00:49:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nutzer generated by hbm2java
 */
public class Nutzer  implements java.io.Serializable {


     private String ntzEmail;
     private Beruf beruf;
     private String ntzPasswort;
     private String ntzName;
     private String ntzVorname;
     private Set lnsiehtans = new HashSet(0);

    public Nutzer() {
    }

	
    public Nutzer(String ntzEmail, Beruf beruf, String ntzPasswort) {
        this.ntzEmail = ntzEmail;
        this.beruf = beruf;
        this.ntzPasswort = ntzPasswort;
    }
    public Nutzer(String ntzEmail, Beruf beruf, String ntzPasswort, String ntzName, String ntzVorname, Set lnsiehtans) {
       this.ntzEmail = ntzEmail;
       this.beruf = beruf;
       this.ntzPasswort = ntzPasswort;
       this.ntzName = ntzName;
       this.ntzVorname = ntzVorname;
       this.lnsiehtans = lnsiehtans;
    }
   
    public String getNtzEmail() {
        return this.ntzEmail;
    }
    
    public void setNtzEmail(String ntzEmail) {
        this.ntzEmail = ntzEmail;
    }
    public Beruf getBeruf() {
        return this.beruf;
    }
    
    public void setBeruf(Beruf beruf) {
        this.beruf = beruf;
    }
    public String getNtzPasswort() {
        return this.ntzPasswort;
    }
    
    public void setNtzPasswort(String ntzPasswort) {
        this.ntzPasswort = ntzPasswort;
    }
    public String getNtzName() {
        return this.ntzName;
    }
    
    public void setNtzName(String ntzName) {
        this.ntzName = ntzName;
    }
    public String getNtzVorname() {
        return this.ntzVorname;
    }
    
    public void setNtzVorname(String ntzVorname) {
        this.ntzVorname = ntzVorname;
    }
    public Set getLnsiehtans() {
        return this.lnsiehtans;
    }
    
    public void setLnsiehtans(Set lnsiehtans) {
        this.lnsiehtans = lnsiehtans;
    }




}


