package bean;
// Generated 20.06.2016 00:49:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sanierungsauftrag generated by hbm2java
 */
public class Sanierungsauftrag  implements java.io.Serializable {


     private Integer snrId;
     private String snrIfcpfad;
     private String snrGebaeude;
     private String snrStatus;
     private String snrBeschreibung;
     private Set lnsiehtans = new HashSet(0);

    public Sanierungsauftrag() {
    }

    public Sanierungsauftrag(String snrIfcpfad, String snrGebaeude, String snrStatus, String snrBeschreibung, Set lnsiehtans) {
       this.snrIfcpfad = snrIfcpfad;
       this.snrGebaeude = snrGebaeude;
       this.snrStatus = snrStatus;
       this.snrBeschreibung = snrBeschreibung;
       this.lnsiehtans = lnsiehtans;
    }
   
    public Integer getSnrId() {
        return this.snrId;
    }
    
    public void setSnrId(Integer snrId) {
        this.snrId = snrId;
    }
    public String getSnrIfcpfad() {
        return this.snrIfcpfad;
    }
    
    public void setSnrIfcpfad(String snrIfcpfad) {
        this.snrIfcpfad = snrIfcpfad;
    }
    public String getSnrGebaeude() {
        return this.snrGebaeude;
    }
    
    public void setSnrGebaeude(String snrGebaeude) {
        this.snrGebaeude = snrGebaeude;
    }
    public String getSnrStatus() {
        return this.snrStatus;
    }
    
    public void setSnrStatus(String snrStatus) {
        this.snrStatus = snrStatus;
    }
    public String getSnrBeschreibung() {
        return this.snrBeschreibung;
    }
    
    public void setSnrBeschreibung(String snrBeschreibung) {
        this.snrBeschreibung = snrBeschreibung;
    }
    public Set getLnsiehtans() {
        return this.lnsiehtans;
    }
    
    public void setLnsiehtans(Set lnsiehtans) {
        this.lnsiehtans = lnsiehtans;
    }




}


