package mysqlBean;
// Generated 12.05.2016 22:04:38 by Hibernate Tools 4.3.1



/**
 * Auftrag generated by hbm2java
 */
public class Auftrag  implements java.io.Serializable {


     private Integer aufNummer;
     private Handwerker handwerker;
     private Schaden schaden;
     private String aufStatus;

    public Auftrag() {
    }

	
    public Auftrag(Handwerker handwerker, Schaden schaden) {
        this.handwerker = handwerker;
        this.schaden = schaden;
    }
    public Auftrag(Handwerker handwerker, Schaden schaden, String aufStatus) {
       this.handwerker = handwerker;
       this.schaden = schaden;
       this.aufStatus = aufStatus;
    }

    public Integer getAufNummer() {
        return this.aufNummer;
    }
    
    public void setAufNummer(Integer aufNummer) {
        this.aufNummer = aufNummer;
    }
    public Handwerker getHandwerker() {
        return this.handwerker;
    }
    
    public void setHandwerker(Handwerker handwerker) {
        this.handwerker = handwerker;
    }
    public Schaden getSchaden() {
        return this.schaden;
    }
    
    public void setSchaden(Schaden schaden) {
        this.schaden = schaden;
    }
    public String getAufStatus() {
        return this.aufStatus;
    }
    
    public void setAufStatus(String aufStatus) {
        this.aufStatus = aufStatus;
    }




}


