package mysqlBean;
// Generated 12.05.2016 22:04:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Schaden generated by hbm2java
 */
public class Schaden  implements java.io.Serializable {


     private Integer sdnId;
     private Gutachter gutachter;
     private Schadensart schadensart;
     private Schadenslage schadenslage;
     private String sdnStatus;
     private String sdnUmfang;
     private Set auftrags = new HashSet(0);
     private Set multimedias = new HashSet(0);

    public Schaden() {
    }

	
    public Schaden(Gutachter gutachter, Schadensart schadensart, Schadenslage schadenslage) {
        this.gutachter = gutachter;
        this.schadensart = schadensart;
        this.schadenslage = schadenslage;
    }
    public Schaden(Gutachter gutachter, Schadensart schadensart, Schadenslage schadenslage, String sdnStatus, String sdnUmfang, Set auftrags, Set multimedias) {
       this.gutachter = gutachter;
       this.schadensart = schadensart;
       this.schadenslage = schadenslage;
       this.sdnStatus = sdnStatus;
       this.sdnUmfang = sdnUmfang;
       this.auftrags = auftrags;
       this.multimedias = multimedias;
    }
   
    public Integer getSdnId() {
        return this.sdnId;
    }
    
    public void setSdnId(Integer sdnId) {
        this.sdnId = sdnId;
    }
    public Gutachter getGutachter() {
        return this.gutachter;
    }
    
    public void setGutachter(Gutachter gutachter) {
        this.gutachter = gutachter;
    }
    public Schadensart getSchadensart() {
        return this.schadensart;
    }
    
    public void setSchadensart(Schadensart schadensart) {
        this.schadensart = schadensart;
    }
    public Schadenslage getSchadenslage() {
        return this.schadenslage;
    }
    
    public void setSchadenslage(Schadenslage schadenslage) {
        this.schadenslage = schadenslage;
    }
    public String getSdnStatus() {
        return this.sdnStatus;
    }
    
    public void setSdnStatus(String sdnStatus) {
        this.sdnStatus = sdnStatus;
    }
    public String getSdnUmfang() {
        return this.sdnUmfang;
    }
    
    public void setSdnUmfang(String sdnUmfang) {
        this.sdnUmfang = sdnUmfang;
    }
    public Set getAuftrags() {
        return this.auftrags;
    }
    
    public void setAuftrags(Set auftrags) {
        this.auftrags = auftrags;
    }
    public Set getMultimedias() {
        return this.multimedias;
    }
    
    public void setMultimedias(Set multimedias) {
        this.multimedias = multimedias;
    }




}


